# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd2b3f94a8cb084aecc7b41292951ecd250ca3984c6d79671011faa103b169b9b64380466537c6d1e3d4e5af0a5f829502a35f9e17b2e1a7f52287889e311e1

test:
  secret_key_base: 7a8ad213c554420e5394659dcb559a743993e8ca3582023d6ebef5890f9d6efc8ae50c405d0bb2137351f306e7f91ebdea8c8fd4c976baf3959cc8ed0020c764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
